### PR TITLE
Blur, background color

### PR DESCRIPTION
**Pull request by AlexeyIS**
Added blur effect to background.
Added custom background color.
Both animated on drag and dismiss.

### CODE REVIEW

**Comment by AlexeyIS** [comment]
Hi @RuiAAPeres, that could be a good option! The only concern I have is that the animation callback has to also be exposessd in order to control blur on drag event and others. What are your thoughts how to approach this?

**Comment by AlexeyIS** [comment]
Thanks @wltrup. How would you suggest to access container view while presenting the modal view from outside of drawer kit?

**Comment by ed-mejia** [comment]
Any chance to include something like this? I honestly think this is an essential feature that should be part of the core library, maybe not a blur background but a basic dimmed option would be grateful, the first thing you will encounter is a designer asking you to add a dim to the background 🤷🏻‍♂️

**Comment by AlexeyIS** [comment]
> Any chance to include something like this? I honestly think this is an essential feature that should be part of the core library, maybe not a blur background but a basic dimmed option would be grateful, the first thing you will encounter is a designer asking you to add a dim to the background 🤷🏻‍♂️

I have a fork with blur background if you need. https://github.com/AlexeyIS/DrawerKit.git

**Comment by ryanb93** [comment]
Stale PR, older than 3 years old, automatically closed.

**Pull request closed without merging**
